### ISSUE TITLE
Region grouping includes adjacent regions

### ISSUE THREAD

**Issue by remidelattre** [JamesBremner/so77307162#11]
Whille attempting to create groups for REG93, I've noticed the number of localities considered is higher than the number of localities that exist in this region. Due to the way the adjacency list works, the algorithm will still use localities from other regions to reach minimum group size as long as they are adjacent and although they provide - or remove - no "de".

Here is an example :
84019 7.060396122 26235  26275  84064 -7.464767248 26326  sum -0.404371

Localities starting with 26 belong to another region, but the algorithm pairs them with localities from region 93 to reach min. group size. The desired output is to create groups with localities that exclusively belong to REG93.  Interestingly enough, it seems like the algorithm cannot retrieve "de" for localities in another region which is actually a good thing. Indeed, making it impossible to create groups with localities that have no "de" seems to be the easier fix, when compared to using different .csvs for every region.

**Comment by JamesBremner** [comment]
Please do not assign issues to more than one person.  If you want my attention to an issue, assign it to me.  If an issue is assigned to you it means that I need you to specify some details or test a feature.

**Comment by JamesBremner** [comment]
This is reproducible

**Comment by JamesBremner** [comment]
Cause:  while localities in the first input field are filtered out if they do not belong to the included region(s), the adjacencies in the second field of included localities are included willy-nilly because at this point their region is unknown.

Fix: I will have to do a two pass read of the input file.  The first pass will identify the localities in the selected regions and the second pass will reject adjacencies that are not identified in the first pass.

**Comment by JamesBremner** [comment]
============
84019 7.060396122 84064 -7.464767248 sum -0.404371
============

**Comment by remidelattre** [comment]
That fixed it. Thank you very much :D
