### ISSUE TITLE
Guided BFS

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/so77307162#4]
I have further enhanced the breadth first search.

Previously, the search blindly explored adjacent localities.  If it happened across an acceptable group then the group was added to the output.

The search now only looks at adjacent localities with bring the group sum closer to zero.

This produces better results in the sense that more localities are assigned to groups.

For example:

```
============
2 1.000000
13 0.000000
15 2.000000
28 -1.000000
38 -2.000000
28 -1.000000
============
3 1.000000
4 2.000000
17 -1.000000
21 -3.000000
25 1.000000
26 0.000000
17 -1.000000
============
5 1.000000
6 -3.000000
30 2.000000
30 2.000000
============
7 -3.000000
35 1.000000
36 2.000000
36 2.000000
============
11 2.000000
23 0.000000
24 1.000000
33 -3.000000
24 1.000000
```

![image](https://github.com/JamesBremner/so77307162/assets/2046227/68fa929b-0e63-4314-8c1d-8f3254f8ed35)

**Comment by JamesBremner** [comment]
released in v0.0.1

**Comment by remidelattre** [comment]
> The search now only looks at adjacent localities with bring the group sum closer to zero.

In trying to maximize the number of localities integrated in groups, wouldn't it be better to first try to maximize _"de"_ within the adjacency parameters and then only look at adjacent localities which bring the group sum closer to zero, starting with the localities with the lowest deficits ? This is the method I try to illustrate in the video, albeit with some mistakes in assessing the optimal path. 

In my opinion, the distribution of "de" values is such that we have a few localities with very high deficits and some with very low deficits. Conversely, we have a few localities with very high surpluses and many with low surpluses. If you immediately attempt to make de = 0, you are going to have smaller groups, and it's likely that at the end, less localities will be in groups. 

This is an important point in the fuction because so far we've compared our algorithm versions based on how many localities remain ungrouped at the end. Minimizing the amount of ungrouped localities within a given sample is our metric for performance assessment.

**Comment by remidelattre** [comment]
![image](https://github.com/JamesBremner/so77307162/assets/148571442/4c7659c8-1723-4e19-b7d5-fd80b780ea2e)


In this example, we avoid F29 because integrating it to the group would considerably reduce group size.

**Comment by remidelattre** [comment]
![image](https://github.com/JamesBremner/so77307162/assets/148571442/365dddda-a729-4be6-82d8-c8f758047297)
this is the groups we can excpect using max adjacency = 4 and de = 0 with the method described above. Hand-made for now :) 
Obviosuly I'd need to keep making groups with increasingly worse starting locations, but this is an encouraging result in terms of group size.

**Comment by JamesBremner** [comment]
>  the amount of ungrouped localities within a given sample is our metric for performance assessment.

FYI I have added to the display a count of assigned and total localities

![image](https://github.com/JamesBremner/so77307162/assets/2046227/d5bbacd0-76b5-4f9f-bb03-81912c608b91)

**Comment by remidelattre** [comment]
This is fairly impressive. May I ask how long it took you to compute the result ? Could we add a condition where minimum group size has to be 5 ? I should probably stop asking and tweak it myself at this point lol. I will run tests tommorow for sure. I cant wait to compare your groups to my handmade ones.

**Comment by JamesBremner** [comment]
> May I ask how long it took you to compute the result ? 

A few seconds  Including reading the input file and outputting the results ( which take longer than the grouping calculation ) 35 seconds.

**Comment by remidelattre** [comment]
Not sure if this is the best issue to discuss the visualization aspect, but do you suggest visualizing one group at a time ? Cant imagine a way to visualize 22000 localities contained in thousands of different groups.

**Comment by JamesBremner** [comment]
Please look at commit https://github.com/JamesBremner/so77307162/commit/4cb8514ce43ff20384f56b325f2c36a154701f03

**Comment by remidelattre** [comment]
Just to be sure : with this version, the program no longer generates graphs but instead shows a list regardless of the size of the dataset, right ?

**Comment by JamesBremner** [comment]
The layout calculation takes a very long time when there are hundreds of localities.  I  doubt that the layout display is useful in such cases anyway, so if there are too many localities in the selected region(s) the layout calculations is skipped.  See commit https://github.com/JamesBremner/so77307162/commit/81cfac768fc791768e5697d98858153bc493d213

**Comment by remidelattre** [comment]
Understood, closing this :)
